# .github/workflows/caller.yml
name: Caller of reusable workflow
on:
  push:

jobs:
  call-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable with input A
        id: callA
        uses: ./.github/workflows/reusable.yml
        with:
          message: "Hello from A"

      - name: Call reusable with input B
        id: callB
        uses: ./.github/workflows/reusable.yml
        with:
          message: "Hello from B"

      - name: Consolidate outputs into log
        run: |
          echo "Output A: ${{ steps.callA.outputs.echoed }}" > consolidated.txt
          echo "Output B: ${{ steps.callB.outputs.echoed }}" >> consolidated.txt
          cat consolidated.txt

      - name: Upload consolidated log
        uses: actions/upload-artifact@v4
        with:
          name: consolidated-log
          path: consolidated.txt
