# .github/workflows/tri-platform-and-artifact.yml
name: Tri-platform jobs + artifact + conditionals
on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print system info (Ubuntu)
        run: |
          echo "OS: $(uname -a)"
          echo "Node version (if installed): $(node --version || echo 'no node')"
          echo "Python: $(python3 --version || echo 'no python')"

      - name: Capture env info to file
        run: |
          echo "sha=${GITHUB_SHA}" > build-info.txt
          echo "repo=${GITHUB_REPOSITORY}" >> build-info.txt
          echo "workspace=${GITHUB_WORKSPACE}" >> build-info.txt
          cat build-info.txt

      - name: Upload ubuntu artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build-info
          path: build-info.txt

  macos:
    runs-on: macos-latest
    needs: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print system info (macOS)
        run: |
          sw_vers || uname -a
          echo "CPU info:"
          sysctl -n machdep.cpu.brand_string || true

      - name: Capture env info to file (mac)
        run: |
          echo "sha=${GITHUB_SHA}" > build-info-mac.txt
          echo "repo=${GITHUB_REPOSITORY}" >> build-info-mac.txt
          echo "workspace=${GITHUB_WORKSPACE}" >> build-info-mac.txt
          cat build-info-mac.txt

      - name: Upload mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-info
          path: build-info-mac.txt

  windows:
    # Wait for ubuntu+macos but still run even if ubuntu failed
    runs-on: windows-latest
    needs: [ubuntu, macos]
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print system info (Windows)
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
          echo "PowerShell version:"
          powershell -Command '$PSVersionTable.PSVersion | Out-String'

      - name: Capture env info to file (windows)
        run: |
          echo sha=%GITHUB_SHA% > build-info-win.txt
          echo repo=%GITHUB_REPOSITORY% >> build-info-win.txt
          echo workspace=%GITHUB_WORKSPACE% >> build-info-win.txt
          type build-info-win.txt

      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-info
          path: build-info-win.txt

      # ---- Conditional steps examples ----
      - name: Only run on main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "This step runs only on main branch"

      - name: Step that runs only if a previous job/step failed
        # failure() checks the job status of the current execution graph
        if: ${{ failure() }}
        run: echo "A previous job or step failed in the workflow."

      - name: Always run this step (regardless of pass/fail)
        if: ${{ always() }}
        run: echo "This always runs in Windows job."
